---
name: 🔄 Update

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    name: 🔄 Update versions & checksums
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.KLOUD_BOT_ORG_PAT }}

      - name: 🔄 Update package versions
        run: ./scripts/update-versions.sh

      - name: 🔄 Update artifact checksums
        run: ./scripts/update-artifact-checksums.sh

      - name: 📝 Commit changes
        uses: kloudkit/ws-meta/.github/actions/commit-and-push@main
        with:
          message: 🔄 Update package versions & artifact checksums

      - name: 🚀 Trigger build
        run: gh workflow run ci.yaml -f monthly=true
        env:
          GH_TOKEN: ${{ secrets.KLOUD_BOT_ORG_PAT }}
